build:
  performance:
    jobs:
      run-grakn:
        machine: grabl-ubuntu-1910-timeout-5h
        type: background
        timeout: "18000"
        script: |
          wget "https://storage.googleapis.com/grabl-dev-secrets/rootCA.jks"
          cp rootCA.jks /tmp/rootCA.jks
          git clone https://github.com/graknlabs/grakn.git
          cd grakn
          git checkout 1.7.0
          bazel build //:assemble-linux-targz
          mkdir dist
          tar -xf ./bazel-bin/grakn-core-all-linux.tar.gz -C ./dist/
          cd ./dist/grakn-core-all-linux/
          SERVER_JAVAOPTS="-Djavax.net.ssl.trustStore=/tmp/rootCA.jks -Djavax.net.ssl.trustStorePassword=changeit" \
            ./grakn server start -- \
            --tracing-uri $GRABL_URI \
            --tracing-username lriuui0x0 \
            --tracing-access-token T30qo2SGRfqYwbdZndtpzVdAEqi4TBEd
          export GRABL_PERFORMANCE_RUN_GRAKN_URI="${HOSTNAME}:48555"
      test-performance-big:
        machine: grabl-ubuntu-1910-timeout-5h
        type: foreground
        timeout: "18000"
        script: |
          wget "https://storage.googleapis.com/grabl-dev-secrets/rootCA.jks"
          cp rootCA.jks /tmp/rootCA.jks
          git clone https://github.com/lolski/simulation.git
          cd simulation
          git fetch origin tracing-test
          git checkout 24fd98e752ed57acbb42d875e8442bb95b1642bb
          bazel run //:simulation -- \
            --keyspace world \
            --grakn-uri $GRABL_PERFORMANCE_RUN_GRAKN_URI \
            --tracing-uri $GRABL_URI \
            --org $GRABL_OWNER \
            --repo $GRABL_REPO \
            --commit $GRABL_COMMIT \
            --username lriuui0x0 \
            --api-token T30qo2SGRfqYwbdZndtpzVdAEqi4TBEd \
            --iterations 1000 \
            --seed 1
    execution:
      - run-grakn
      - test-performance-big:
          depends: [run-grakn]

