build:
  performance:
    jobs:
      run-grakn:
        machine: grabl-ubuntu-2004-long
        type: background
        timeout: "18000"
        script: |
          mkdir -p ~/.config/gcloud/
          echo $GRABL_RBE_CREDENTIAL > ~/.config/gcloud/application_default_credentials.json
          wget "https://storage.googleapis.com/grabl-dev-secrets/rootCA.jks"
          cp rootCA.jks /tmp/rootCA.jks
          git clone https://github.com/graknlabs/grakn.git
          cd grakn
          git checkout 1.7.0
          bazel build --config=rbe //:assemble-linux-targz
          mkdir dist
          tar -xf ./bazel-bin/grakn-core-all-linux.tar.gz -C ./dist/
          cd ./dist/grakn-core-all-linux/
          SERVER_JAVAOPTS="-Djavax.net.ssl.trustStore=/tmp/rootCA.jks -Djavax.net.ssl.trustStorePassword=changeit" \
            ./grakn server start -- \
            --tracing-uri $GRABL_TRACING_URI \
            --tracing-username lriuui0x0 \
            --tracing-access-token 73yocFPsn67tmx9YDVWLrwWLaKpyC9XN
          export GRABL_EXPORT_PERFORMANCE_GRAKN_URI="${HOSTNAME}:48555"
      test-performance-big:
        machine: grabl-ubuntu-2004-long
        type: foreground
        timeout: "18000"
        script: |
          mkdir -p ~/.config/gcloud/
          echo $GRABL_RBE_CREDENTIAL > ~/.config/gcloud/application_default_credentials.json
          wget "https://storage.googleapis.com/grabl-dev-secrets/rootCA.jks"
          cp rootCA.jks /tmp/rootCA.jks
          git clone https://github.com/lolski/simulation.git
          cd simulation
          git fetch --tags
          git checkout tracing-test-v1
          bazel run --config=rbe //:simulation -- \
            --keyspace world \
            --grakn-uri $GRABL_EXPORT_PERFORMANCE_GRAKN_URI \
            --tracing-uri $GRABL_TRACING_URI \
            --org $GRABL_OWNER \
            --repo $GRABL_REPO \
            --commit $GRABL_COMMIT \
            --username lriuui0x0 \
            --api-token 73yocFPsn67tmx9YDVWLrwWLaKpyC9XN \
            --iterations 5 \
            --seed 1 \
            -f 1
    execution:
      - run-grakn
      - test-performance-big:
          depends: [run-grakn]

