build:
  performance:
    jobs:
      run-grakn:
        machine: grabl-ubuntu-1910-cache-run-grakn
        type: background
        timeout: "18000"
        script: |
          wget "https://storage.cloud.google.com/grabl-dev-secrets/rootCA.jks"
          cp rootCA.jks /tmp/rootCA.jks
          # git clone https://github.com/lolski/grakn.git
          cd grakn
          git checkout f04512e47c6b8b4ed87239870d07b3ce7f2c58ee
          bazel build //:assemble-linux-targz
          mkdir dist
          tar -xf ./bazel-bin/grakn-core-all-linux.tar.gz -C ./dist/
          cd ./dist/grakn-core-all-linux/
          SERVER_JAVAOPTS="-Djavax.net.ssl.trustStore=/tmp/rootCA.jks -Djavax.net.ssl.trustStorePassword=changeit" \
            ./grakn server start -- \
            # --tracing-enabled \
            --tracing-uri $GRABL_URI \
            --tracing-username lriuui0x0 \
            --tracing-access-token T30qo2SGRfqYwbdZndtpzVdAEqi4TBEd
          export GRABL_PERFORMANCE_RUN_GRAKN_URI="${HOSTNAME}:48555"
      test-performance-big:
        machine: grabl-ubuntu-1910-cache-test-performance-big
        type: foreground
        timeout: "18000"
        script: |
          wget "https://storage.cloud.google.com/grabl-dev-secrets/rootCA.jks"
          cp rootCA.jks /tmp/rootCA.jks
          # git clone https://github.com/lolski/simulation.git
          cd simulation
          git fetch origin tracing-test
          git checkout fc5942f1ebc92aee24cfafd9a27e97020ae7e1c5
          bazel run //:simulation -- \
            --jvm_flag="-Djavax.net.ssl.trustStore=/tmp/rootCA.jks" --jvm_flag="-Djavax.net.ssl.trustStorePassword=changeit" 
            --keyspace world \
            --grakn-uri $GRABL_PERFORMANCE_RUN_GRAKN_URI \
            --tracing-uri $GRABL_URI \
            --org $GRABL_OWNER \
            --repo $GRABL_REPO \
            --commit $GRABL_COMMIT \
            --username lriuui0x0 \
            --api-token T30qo2SGRfqYwbdZndtpzVdAEqi4TBEd \
            --iterations 1 \
            --seed 1
    execution:
      - run-grakn
      - test-performance-big:
          depends: [run-grakn]

